package com.app.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Entity
@Table(name = "geysers")
public class Geyser {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column
    private String brand;

    @Column
    private String model;

    @Column
    private double capacity; // In liters

    @Column
    private String hasThermostat;
    
   

    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public double getCapacity() {
		return capacity;
	}

	public void setCapacity(double capacity) {
		this.capacity = capacity;
	}

	public String getHasThermostat() {
		return hasThermostat;
	}

	public void setHasThermostat(String hasThermostat) {
		this.hasThermostat = hasThermostat;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getIsUnderWarranty() {
		return isUnderWarranty;
	}

	public void setIsUnderWarranty(String isUnderWarranty) {
		this.isUnderWarranty = isUnderWarranty;
	}

	public String getIsServiceRequired() {
		return isServiceRequired;
	}

	public void setIsServiceRequired(String isServiceRequired) {
		this.isServiceRequired = isServiceRequired;
	}

	@Column
    private double price;

    // Additional fields for geyser repair service
    @Column
    private String isUnderWarranty;

    @Column
    private String isServiceRequired;

    
    // Getters, setters, equals, hashCode, and toString methods generated by Lombok
}
