package com.app.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Entity
@Table(name = "water_purifiers")
public class WaterPurifier {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column
    private String brand;

    @Column
    private String model;

    @Column
    private String purificationTechnology;

    @Column
    private double capacity; // In liters

    @Column
    private String hasUVFilter;

    @Column
    private double price;

    // Additional fields for water purifier repair service
    @Column
    private String isUnderWarranty;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getPurificationTechnology() {
		return purificationTechnology;
	}

	public void setPurificationTechnology(String purificationTechnology) {
		this.purificationTechnology = purificationTechnology;
	}

	public double getCapacity() {
		return capacity;
	}

	public void setCapacity(double capacity) {
		this.capacity = capacity;
	}

	public String getHasUVFilter() {
		return hasUVFilter;
	}

	public void setHasUVFilter(String hasUVFilter) {
		this.hasUVFilter = hasUVFilter;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getIsUnderWarranty() {
		return isUnderWarranty;
	}

	public void setIsUnderWarranty(String isUnderWarranty) {
		this.isUnderWarranty = isUnderWarranty;
	}

    // Getters, setters, equals, hashCode, and toString methods generated by Lombok
}
